# Generated by scripts/release/generate-formula.sh; do not edit.
class Agefreighter < Formula
  desc "Validated, resumable graph migration into Apache AGE"
  homepage "https://github.com/rioriost/agefreighter"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rioriost/agefreighter/releases/download/v2.4.0/agefreighter_v2.4.0_darwin_arm64.tar.gz"
      sha256 "7ef852886467fc9bb2006d568e50ce39a82ae017023b8aea2ec2cdca1f044536"
    else
      url "https://github.com/rioriost/agefreighter/releases/download/v2.4.0/agefreighter_v2.4.0_darwin_amd64.tar.gz"
      sha256 "6f0667362ff396d2df6a286eea679e6ca63f2d0ead55746e97fc8189e39b97f4"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/rioriost/agefreighter/releases/download/v2.4.0/agefreighter_v2.4.0_linux_arm64.tar.gz"
      sha256 "e3a3ecc024d1cd4805bb2f5a9692718175db0c3af7d5c535f2bd7306726e75e4"
    else
      url "https://github.com/rioriost/agefreighter/releases/download/v2.4.0/agefreighter_v2.4.0_linux_amd64.tar.gz"
      sha256 "666c6c88b6081b9c1878cd6e564e85eb9b26ec16c3f3288cba14709b6413fa80"
    end
  end

  def install
    bin.install "agefreighter"
    bin.install "agefreighter-tools"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agefreighter version")
    assert_match version.to_s, shell_output("#{bin}/agefreighter-tools version")
  end
end
