# Generated by scripts/release/generate-formula.sh; do not edit.
class Agefreighter < Formula
  desc "Validated, resumable graph migration into Apache AGE"
  homepage "https://github.com/rioriost/agefreighter"
  version "2.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rioriost/agefreighter/releases/download/v2.3.1/agefreighter_v2.3.1_darwin_arm64.tar.gz"
      sha256 "36c586b029620ad41ed463e301f7f47ff7e025b079638ed0e67ede3eaae3987c"
    else
      url "https://github.com/rioriost/agefreighter/releases/download/v2.3.1/agefreighter_v2.3.1_darwin_amd64.tar.gz"
      sha256 "7f3f7fae0202a2460c5f7e904fb312bce5266cce5fc997f4835e4530e3dce262"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/rioriost/agefreighter/releases/download/v2.3.1/agefreighter_v2.3.1_linux_arm64.tar.gz"
      sha256 "7db1ad782b4ffbc6713ee37d06c8e6c194cc533e75b8baad865dd44839b326dc"
    else
      url "https://github.com/rioriost/agefreighter/releases/download/v2.3.1/agefreighter_v2.3.1_linux_amd64.tar.gz"
      sha256 "953a5bc826d4700b95496eaf97a054875cd983cc77f0c39db519500346563f93"
    end
  end

  def install
    bin.install "agefreighter"
    bin.install "agefreighter-tools"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agefreighter version")
    assert_match version.to_s, shell_output("#{bin}/agefreighter-tools version")
  end
end
