# Generated by scripts/release/generate-formula.sh; do not edit.
class Agefreighter < Formula
  desc "Validated, resumable graph migration into Apache AGE"
  homepage "https://github.com/rioriost/agefreighter"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rioriost/agefreighter/releases/download/v2.0.0/agefreighter_v2.0.0_darwin_arm64.tar.gz"
      sha256 "2768448eb22d13429aaace9dc27ba2cfd21096389d96893b3f61f2447073d30d"
    else
      url "https://github.com/rioriost/agefreighter/releases/download/v2.0.0/agefreighter_v2.0.0_darwin_amd64.tar.gz"
      sha256 "ac315bf38f3178eea46b49c1a331cdb02794e09ef3cdb23a4a10f08adcb7a7e8"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/rioriost/agefreighter/releases/download/v2.0.0/agefreighter_v2.0.0_linux_arm64.tar.gz"
      sha256 "cbe0a5cd0b8e04e577787a3f9285c69403d59216a6e8193094c2023456024286"
    else
      url "https://github.com/rioriost/agefreighter/releases/download/v2.0.0/agefreighter_v2.0.0_linux_amd64.tar.gz"
      sha256 "fe81041c44bd299f9c078dd994370737b4679ab6f3b85d89834763dbea901866"
    end
  end

  def install
    bin.install "agefreighter"
    bin.install "agefreighter-tools"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agefreighter version")
    assert_match version.to_s, shell_output("#{bin}/agefreighter-tools version")
  end
end
